# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'RNFeaturePOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNFeaturePOC
  pod 'Alamofire', '~> 5.4'

  target 'RNFeaturePOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNFeaturePOCUITests' do
    # Pods for testing
  end

end
